### PR TITLE
Add search input styles

### PR DESCRIPTION
**Pull request by vednoc**
Before:
image

After:
image

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Hi @vednoc 
Thanks, is this the same color input as the top search bar? I would prefer to have it match and I agree it inst ideal ;)

**Comment by the-j0k3r** [comment]
The eye dropper claims its `#4a4d53` the top search input bg

**Comment by the-j0k3r** [comment]
Ill merge this and tweak it and push an update.. Thanks again. very appreciated :)

**Comment by the-j0k3r** [comment]
capture

Looks even better thanks to you, update incoming in a few

**Comment by vednoc** [comment]
I didn't want to add another color so I took the one that looks the best. :smiley: It looks even better now, good job! :+1:

**Comment by the-j0k3r** [comment]
Dont worry about adding colors, for reference I use the existing pallete Discod uses in the dark style, so if the colors exist, they are fair game.

The general idea is to make it match as closely as possible. :)

BTW may I ask how did you find this style, are you on Stylus channel at Discord?

**Comment by vednoc** [comment]
Sure thing, I'll keep that in mind. :smiley: 

Yeah! I'll ping you over there. :laughing:

**Pull request merged**
