### PR TITLE
:construction: fix install link

### PR DESCRIPTION
**Pull request by vednoc**

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Thanks, :+1:

**Comment by the-j0k3r** [comment]
So you know https://github.com/style-it-themes/discord-inspired-bits-dark/commit/8138b5577ba162a3e85bb0272e6c469f84048429 the actual update link was also bummed.

If you manually update it, it should be OK for next updates ;)

Thank you again :smile:

**Comment by vednoc** [comment]
Nice! I noticed that way too late. :smile:

**Comment by the-j0k3r** [comment]
Sorry, for any inconvenience caused.

**Pull request merged**
